local E, C, L = select(2, ...):unpack()

------------------------------------------------------------------------
-- Bag Localization
------------------------------------------------------------------------

-- Item type strings (used by legacy filters if needed)
L.BAG_ARMOR = GetItemClassInfo(4)
L.BAG_BATTLEPET = GetItemClassInfo(17)
L.BAG_CONSUMABLES = GetItemClassInfo(0)
L.BAG_GEM = GetItemClassInfo(3)
L.BAG_QUEST = GetItemClassInfo(12)
L.BAG_TRADES = GetItemClassInfo(7)
L.BAG_WEAPON = GetItemClassInfo(2)

-- Sub-container labels
L.BAG_LABEL_EQUIPMENT = BAG_FILTER_EQUIPMENT
L.BAG_LABEL_EQUIPSET = LOOT_JOURNAL_ITEM_SETS
L.BAG_LABEL_CONSUMABLE = BAG_FILTER_CONSUMABLES
L.BAG_LABEL_GOODS = AUCTION_CATEGORY_TRADE_GOODS
L.BAG_LABEL_QUEST = AUCTION_CATEGORY_QUEST_ITEMS
L.BAG_LABEL_COLLECTION = COLLECTIONS
L.BAG_LABEL_JUNK = BAG_FILTER_JUNK
L.BAG_LABEL_REAGENT = REAGENT_BANK
L.BAG_LABEL_AZERITE = AZERITE_ARMOR
L.BAG_LABEL_AOE = ITEM_ACCOUNTBOUND_UNTIL_EQUIP
L.BAG_LABEL_ANIMA = POWER_TYPE_ANIMA
L.BAG_LABEL_STONE = C_Spell.GetSpellName(404861) or "Crests"
L.BAG_LABEL_LEGACY = EXPANSION_FILTER_OLD or "Legacy"
L.BAG_LABEL_LOWER = ITEM_LEVEL_ABBR or "iLvl"
L.BAG_LABEL_DECOR = AUCTION_CATEGORY_HOUSING or "Decor"

-- Hint strings
L.BAG_HINT_TOGGLE = BACKPACK_TOOLTIP
L.BAG_HINT_RESTACK = BAG_CLEANUP_BAGS or "Sort"
L.BAG_HINT_RESET_NEW = RESET
L.BAG_HINT_DEPOSIT = REAGENTBANK_DEPOSIT
L.BAG_HINT_ACOUNT_DEPOSIT_INCLUDE_REAGENTS = BANK_TAB_DEPOSIT_REAGENTS_CHECKBOX_LABEL or "Include reagents"
