local E, C, L = select(2, ...):unpack()

------------------------------------------------------------------------
-- Bag Localization
------------------------------------------------------------------------

L.BAG_ARMOR = GetItemClassInfo(4)
L.BAG_BATTLEPET = GetItemClassInfo(17)
L.BAG_CONSUMABLES = GetItemClassInfo(0)
L.BAG_GEM = GetItemClassInfo(3)
L.BAG_QUEST = GetItemClassInfo(12)
L.BAG_TRADES = GetItemClassInfo(7)
L.BAG_WEAPON = GetItemClassInfo(2)

L.BAG_CAPTIONS_BANK = BANK
L.BAG_CAPTIONS_BANKREAGENT = REAGENT_BANK
L.BAG_CAPTIONS_BANKSETS = LOOT_JOURNAL_ITEM_SETS
L.BAG_CAPTIONS_BANKARMOR = BAG_FILTER_EQUIPMENT
L.BAG_CAPTIONS_BANKGEM = AUCTION_CATEGORY_GEMS
L.BAG_CAPTIONS_BANKQUEST = AUCTION_CATEGORY_QUEST_ITEMS
L.BAG_CAPTIONS_BANKPET = AUCTION_CATEGORY_BATTLE_PETS
L.BAG_CAPTIONS_BANKTRADE = AUCTION_CATEGORY_TRADE_GOODS
L.BAG_CAPTIONS_BANKCONS = BAG_FILTER_CONSUMABLES
L.BAG_CAPTIONS_BANKJUNK = BAG_FILTER_JUNK
L.BAG_CAPTIONS_BANKACCOUNT = ACCOUNT_BANK_PANEL_TITLE

L.BAG_CAPTIONS_JUNK = BAG_FILTER_JUNK
L.BAG_CAPTIONS_ITEMSETS = LOOT_JOURNAL_ITEM_SETS
L.BAG_CAPTIONS_ARMOR = BAG_FILTER_EQUIPMENT
L.BAG_CAPTIONS_GEM = AUCTION_CATEGORY_GEMS
L.BAG_CAPTIONS_QUEST = AUCTION_CATEGORY_QUEST_ITEMS
L.BAG_CAPTIONS_CONSUMABLES = BAG_FILTER_CONSUMABLES
L.BAG_CAPTIONS_TRADEGOODS = AUCTION_CATEGORY_TRADE_GOODS
L.BAG_CAPTIONS_BATTLEPET = AUCTION_CATEGORY_BATTLE_PETS
L.BAG_CAPTIONS_BAG = INVENTORY_TOOLTIP

L.BAG_HINT_TOGGLE = "Toggle Bags"
L.BAG_HINT_RESET_NEW = "Reset New"
L.BAG_HINT_RESTACK = "Sort"
L.BAG_HINT_ACOUNT_DEPOSIT_INCLUDE_REAGENTS = "Include Reagents"
