local E, C, L = select(2, ...):unpack()

------------------------------------------------------------------------
-- Bag Localization
------------------------------------------------------------------------

-- Item type strings (legacy reference)
L.BAG_ARMOR = GetItemClassInfo(4)
L.BAG_BATTLEPET = GetItemClassInfo(17)
L.BAG_CONSUMABLES = GetItemClassInfo(0)
L.BAG_GEM = GetItemClassInfo(3)
L.BAG_QUEST = GetItemClassInfo(12)
L.BAG_TRADES = GetItemClassInfo(7)
L.BAG_WEAPON = GetItemClassInfo(2)

-- Container captions
L.BAG_CAPTIONS_BANK = BANK
L.BAG_CAPTIONS_BANKREAGENT = REAGENT_BANK
L.BAG_CAPTIONS_BANKSETS = LOOT_JOURNAL_ITEM_SETS
L.BAG_CAPTIONS_BANKEQUIPMENT = BAG_FILTER_EQUIPMENT
L.BAG_CAPTIONS_BANKQUEST = AUCTION_CATEGORY_QUEST_ITEMS
L.BAG_CAPTIONS_BANKTRADE = AUCTION_CATEGORY_TRADE_GOODS
L.BAG_CAPTIONS_BANKCONS = BAG_FILTER_CONSUMABLES
L.BAG_CAPTIONS_BANKCOLLECTION = COLLECTIONS
L.BAG_CAPTIONS_BANKJUNK = BAG_FILTER_JUNK
L.BAG_CAPTIONS_BANKACCOUNT = ACCOUNT_BANK_PANEL_TITLE

L.BAG_CAPTIONS_JUNK = BAG_FILTER_JUNK
L.BAG_CAPTIONS_ITEMSETS = LOOT_JOURNAL_ITEM_SETS
L.BAG_CAPTIONS_EQUIPMENT = BAG_FILTER_EQUIPMENT
L.BAG_CAPTIONS_QUEST = AUCTION_CATEGORY_QUEST_ITEMS
L.BAG_CAPTIONS_CONSUMABLES = BAG_FILTER_CONSUMABLES
L.BAG_CAPTIONS_TRADEGOODS = AUCTION_CATEGORY_TRADE_GOODS
L.BAG_CAPTIONS_COLLECTION = COLLECTIONS
L.BAG_CAPTIONS_AOE = ITEM_ACCOUNTBOUND_UNTIL_EQUIP
L.BAG_CAPTIONS_DECOR = AUCTION_CATEGORY_HOUSING or "Decor"
L.BAG_CAPTIONS_LEGACY = EXPANSION_FILTER_OLD or "Legacy"
L.BAG_CAPTIONS_NEWITEMS = NEW
L.BAG_CAPTIONS_BAG = INVENTORY_TOOLTIP

-- Hint strings
L.BAG_HINT_TOGGLE = BACKPACK_TOOLTIP
L.BAG_HINT_RESTACK = BAG_CLEANUP_BAGS or "Sort"
L.BAG_HINT_RESET_NEW = RESET
L.BAG_HINT_DEPOSIT = REAGENTBANK_DEPOSIT
L.BAG_HINT_ACOUNT_DEPOSIT_INCLUDE_REAGENTS = BANK_TAB_DEPOSIT_REAGENTS_CHECKBOX_LABEL or "Include reagents"
